import pandas as pd


def detect_event_bursts(
    logs: pd.DataFrame,
    threshold: int = 5,
    window_minutes: int = 10,
) -> pd.DataFrame:
    """
    Detect repeated Warning and Error events generated by the same
    machine and source within a defined time window.
    """

    required_columns = {
        "MachineName",
        "Source",
        "EntryType",
        "TimeGenerated",
    }

    missing_columns = required_columns - set(logs.columns)

    if missing_columns:
        raise ValueError(
            f"Missing required columns: {sorted(missing_columns)}"
        )

    working_logs = logs.copy()

    working_logs["TimeGenerated"] = pd.to_datetime(
        working_logs["TimeGenerated"],
        errors="coerce",
    )

    working_logs = working_logs.dropna(subset=["TimeGenerated"])

    # Select both warning and error events
    suspicious_logs = working_logs[
        working_logs["EntryType"]
        .astype(str)
        .str.lower()
        .isin(["warning", "error"])
    ].copy()

    suspicious_logs["TimeWindow"] = suspicious_logs[
        "TimeGenerated"
    ].dt.floor(f"{window_minutes}min")

    alerts = (
        suspicious_logs.groupby(
            [
                "MachineName",
                "Source",
                "EntryType",
                "TimeWindow",
            ],
            dropna=False,
        )
        .size()
        .reset_index(name="EventCount")
    )

    alerts = alerts[alerts["EventCount"] >= threshold].copy()

    alerts["AlertName"] = alerts["EntryType"].apply(
        lambda event_type: (
            "Repeated Windows Error Events"
            if str(event_type).lower() == "error"
            else "Repeated Windows Warning Events"
        )
    )

    def assign_severity(row):
        event_type = str(row["EntryType"]).lower()
        count = row["EventCount"]

        if event_type == "error" and count >= 15:
            return "High"

        if event_type == "warning" and count >= 20:
            return "High"

        return "Medium"

    alerts["Severity"] = alerts.apply(assign_severity, axis=1)

    return alerts.sort_values(
        by="EventCount",
        ascending=False,
    )