import pandas as pd


def detect_event_bursts(
    logs: pd.DataFrame,
    threshold: int = 5,
    window_minutes: int = 10,
) -> pd.DataFrame:
    """
    Detect repeated Medium and High severity events generated by the
    same device and event source within a selected time window.

    The function expects logs using the normalized AI-SOC schema.
    """

    required_columns = {
        "DeviceName",
        "EventSource",
        "EventSeverity",
        "EventTime",
    }

    missing_columns = required_columns - set(logs.columns)

    if missing_columns:
        raise ValueError(
            "Normalized logs are missing detection columns: "
            f"{sorted(missing_columns)}"
        )

    if threshold < 1:
        raise ValueError("The detection threshold must be at least 1.")

    if window_minutes < 1:
        raise ValueError("The time window must be at least 1 minute.")

    working_logs = logs.copy()

    working_logs["EventTime"] = pd.to_datetime(
        working_logs["EventTime"],
        errors="coerce",
    )

    working_logs = working_logs.dropna(
        subset=[
            "EventTime",
            "DeviceName",
            "EventSource",
            "EventSeverity",
        ]
    )

    working_logs["EventSeverityNormalized"] = (
        working_logs["EventSeverity"]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    # Medium represents the original Warning events.
    # High represents the original Error events.
    suspicious_logs = working_logs[
        working_logs["EventSeverityNormalized"].isin(
            ["medium", "high"]
        )
    ].copy()

    if suspicious_logs.empty:
        return pd.DataFrame(
            columns=[
                "DeviceName",
                "EventSource",
                "EventSeverity",
                "TimeWindow",
                "EventCount",
                "AlertName",
                "Severity",
            ]
        )

    suspicious_logs["TimeWindow"] = suspicious_logs[
        "EventTime"
    ].dt.floor(f"{window_minutes}min")

    alerts = (
        suspicious_logs.groupby(
            [
                "DeviceName",
                "EventSource",
                "EventSeverityNormalized",
                "TimeWindow",
            ],
            dropna=False,
        )
        .size()
        .reset_index(name="EventCount")
    )

    alerts = alerts[
        alerts["EventCount"] >= threshold
    ].copy()

    alerts = alerts.rename(
        columns={
            "EventSeverityNormalized": "EventSeverity",
        }
    )

    alerts["EventSeverity"] = (
        alerts["EventSeverity"]
        .str.capitalize()
    )

    alerts["AlertName"] = alerts["EventSeverity"].apply(
        lambda severity: (
            "Repeated High-Severity Events"
            if severity == "High"
            else "Repeated Medium-Severity Events"
        )
    )

    def assign_alert_severity(row: pd.Series) -> str:
        event_severity = str(row["EventSeverity"]).lower()
        event_count = int(row["EventCount"])

        if event_severity == "high" and event_count >= 15:
            return "High"

        if event_severity == "medium" and event_count >= 20:
            return "High"

        return "Medium"

    alerts["Severity"] = alerts.apply(
        assign_alert_severity,
        axis=1,
    )

    return alerts.sort_values(
        by=[
            "Severity",
            "EventCount",
        ],
        ascending=[
            True,
            False,
        ],
    ).reset_index(drop=True)